"""Entry points that a Flower experiment provides to the ServerApp and ClientApp."""

import typing as t
from dataclasses import dataclass
from pathlib import Path

from flwr.app import Context, Message
from flwr.serverapp import Grid


@dataclass(frozen=True)
class ServerPaths:
    """Paths available to the server side of an experiment.

    Attributes:
        output_dir:
          Directory for the outputs of this run. May not exist yet.
    """

    output_dir: Path


@dataclass(frozen=True)
class ClientPaths:
    """Paths available to the client side of an experiment.

    Attributes:
        log_dir:
          Directory for this client's training logs.
    """

    log_dir: Path


@dataclass(frozen=True)
class ClientDataset:
    """Dataset of one client, generated by gridfm-datakit.

    Attributes:
        data_dir:
          Directory holding one subdirectory per network.
        networks:
          Names of the networks to use, each a subdirectory of `data_dir`.
        scenarios:
          Maximum number of scenarios to use per network, in the order of
          `networks`.

    Raises:
        ValueError:
          If `networks` is empty or `scenarios` differs from it in length.
    """

    data_dir: Path
    networks: tuple[str, ...]
    scenarios: tuple[int, ...]

    def __post_init__(self) -> None:
        """Validate the lengths of `networks` and `scenarios`.

        Raises:
            ValueError:
              If `networks` is empty or `scenarios` differs from it in length.
        """
        if not self.networks:
            raise ValueError("A client dataset needs at least one network.")
        if len(self.scenarios) != len(self.networks):
            raise ValueError(
                f"Got {len(self.networks)} networks but {len(self.scenarios)} "
                "scenario counts. Give one scenario count per network."
            )


class ServerMain(t.Protocol):
    """Server side of an experiment, run once per Flower run."""

    def __call__(self, grid: Grid, context: Context, paths: ServerPaths) -> None:
        """Run the experiment's server logic."""
        ...


class ClientHandler(t.Protocol):
    """Client handler of an experiment, run once per received message."""

    def __call__(
        self, msg: Message, context: Context, dataset: ClientDataset, paths: ClientPaths
    ) -> Message:
        """Handle `msg` and return the reply."""
        ...


@dataclass(frozen=True)
class Experiment:
    """Entry points of one Flower experiment.

    Attributes:
        server_main:
          Server side, called by the ServerApp.
        client_train:
          Client handler for train messages.
        client_evaluate:
          Client handler for evaluate messages.
    """

    server_main: ServerMain
    client_train: ClientHandler
    client_evaluate: ClientHandler
